mkdir binOgre

copy lib\x64\OgreMain.dll binOgre
copy lib\x64\OgreOverlay.dll binOgre
copy lib\x64\OgreBites.dll binOgre
copy lib\x64\OgrePaging.dll binOgre
copy lib\x64\OgreRTShaderSystem.dll binOgre
copy lib\x64\OgreTerrain.dll binOgre
copy lib\x64\OgreVolume.dll binOgre
copy lib\x64\OgreMeshLodGenerator.dll binOgre
copy lib\x64\OgreHLMS.dll binOgre
copy lib\x64\Plugin_BSPSceneManager.dll binOgre
copy lib\x64\Plugin_CgProgramManager.dll binOgre
copy lib\x64\Plugin_OctreeSceneManager.dll binOgre
copy lib\x64\Plugin_OctreeZone.dll binOgre
copy lib\x64\Plugin_ParticleFX.dll binOgre
copy lib\x64\Plugin_PCZSceneManager.dll binOgre
copy lib\x64\RenderSystem_Direct3D9.dll binOgre
copy lib\x64\RenderSystem_Direct3D11.dll binOgre
copy lib\x64\RenderSystem_GL.dll binOgre
copy lib\x64\RenderSystem_GL3Plus.dll binOgre
copy lib\x64\SDL2.dll binOgre

copy lib\x64\Sample_AtomicCounters.dll binOgre
copy lib\x64\Sample_BSP.dll binOgre
copy lib\x64\Sample_BezierPatch.dll binOgre
copy lib\x64\Sample_CameraTrack.dll binOgre
copy lib\x64\Sample_CelShading.dll binOgre
copy lib\x64\Sample_Character.dll binOgre
copy lib\x64\Sample_Compositor.dll binOgre
copy lib\x64\Sample_Compute.dll binOgre
copy lib\x64\Sample_CubeMapping.dll binOgre
copy lib\x64\Sample_DeferredShading.dll binOgre
copy lib\x64\Sample_Dot3Bump.dll binOgre
copy lib\x64\Sample_DualQuaternion.dll binOgre
copy lib\x64\Sample_DynTex.dll binOgre
copy lib\x64\Sample_EndlessWorld.dll binOgre
copy lib\x64\Sample_FacialAnimation.dll binOgre
copy lib\x64\Sample_Fresnel.dll binOgre
copy lib\x64\Sample_Grass.dll binOgre
copy lib\x64\Sample_Hair.dll binOgre
copy lib\x64\Sample_HLMS.dll binOgre
copy lib\x64\Sample_Instancing.dll binOgre
copy lib\x64\Sample_Island.dll binOgre
copy lib\x64\Sample_Isosurface.dll binOgre
copy lib\x64\Sample_Lighting.dll binOgre
copy lib\x64\Sample_MeshLod.dll binOgre
copy lib\x64\Sample_NewInstancing.dll binOgre
copy lib\x64\Sample_Ocean.dll binOgre
copy lib\x64\Sample_ParticleFX.dll binOgre
copy lib\x64\Sample_ParticleGS.dll binOgre
copy lib\x64\Sample_PBR.dll binOgre
copy lib\x64\Sample_PNTriangles.dll binOgre
copy lib\x64\Sample_ShaderSystem.dll binOgre
copy lib\x64\Sample_ShaderSystemMultiLight.dll binOgre
copy lib\x64\Sample_ShaderSystemTexturedFog.dll binOgre
copy lib\x64\Sample_Shadows.dll binOgre
copy lib\x64\Sample_SkeletalAnimation.dll binOgre
copy lib\x64\Sample_SkyBox.dll binOgre
copy lib\x64\Sample_SkyDome.dll binOgre
copy lib\x64\Sample_SkyPlane.dll binOgre
copy lib\x64\Sample_Smoke.dll binOgre
copy lib\x64\Sample_SphereMapping.dll binOgre
copy lib\x64\Sample_SSAO.dll binOgre
copy lib\x64\Sample_Terrain.dll binOgre
copy lib\x64\Sample_TerrainTessellation.dll binOgre
copy lib\x64\Sample_Tessellation.dll binOgre
copy lib\x64\Sample_TextureArray.dll binOgre
copy lib\x64\Sample_TextureFX.dll binOgre
copy lib\x64\Sample_Transparency.dll binOgre
copy lib\x64\Sample_VolumeCSG.dll binOgre
copy lib\x64\Sample_VolumeTerrain.dll binOgre
copy lib\x64\Sample_VolumeTex.dll binOgre
copy lib\x64\Sample_Water.dll binOgre

copy ..\libCG\x64\cg.dll binOgre
copy ..\lib\x64\OIS.dll binOgre

copy OgreData\plugins.cfg binOgre
copy OgreData\resources.cfg binOgre
copy OgreData\samples.cfg binOgre
copy OgreData\quakemap.cfg binOgre

copy x64\Release\SampleBrowser.exe binOgre
copy x64\Release\BaseSample.exe binOgre
copy x64\Release\BaseCEGUI.exe binOgre